/**
 * Bake the deck tiles the game actually draws.
 *
 * The geomorph library is 634 MB and 7,252 files. A jam build cannot carry
 * that and does not need to: the board draws one hundred-foot section per
 * compartment, so the only tiles worth shipping are the hundred-foot ones
 * whose plating is read off the artwork rather than guessed from a folder
 * name. That is 259 files and about eleven megabytes.
 *
 *   node tools/deck/bake.mjs [path to vuvko_works]
 *
 * Reads the downscaled set prepared for the other half of this project —
 * already 4 px/ft webp with a ten-foot bleed — and writes what is kept into
 * `public/deck/`, with an index and the licence beside it. Run it again and it
 * overwrites; nothing here is edited by hand.
 *
 * The art is CC BY-NC (`public/deck/LICENCE.md`). That is a decision about the
 * whole project and not about this script: anything built with these tiles has
 * to stay non-commercial.
 */
import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const salvor = join(here, "..", "..");
const source = process.argv[2] ?? join(salvor, "..", "..", "..", "vuvko_works");

const taxonomy = join(source, "game", "src", "assets", "tiles", "taxonomy.json");
const tiles = join(source, "game", "public", "geomorphs");
if (!existsSync(taxonomy)) {
  console.error(`no taxonomy at ${taxonomy}\nusage: node tools/deck/bake.mjs [path to vuvko_works]`);
  process.exit(1);
}

const tax = JSON.parse(readFileSync(taxonomy, "utf8")).tiles;
const out = join(salvor, "public", "deck");
rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, "t"), { recursive: true });

/* A short, flat name per tile. The archive's own paths carry brackets, commas
   and spaces, and a URL that needs escaping is a URL that will be got wrong
   once. The hash is of the path, so a tile keeps its name across a re-bake. */
const name = (path) => createHash("sha1").update(path).digest("hex").slice(0, 12);

const index = [];
let bytes = 0;
for (const [path, tile] of Object.entries(tax)) {
  const ft = tile.ft ?? [];
  /* One compartment is one section is one hundred feet square. Anything else
     would have to be cut or stretched to sit under a hexagon. */
  if (ft[0] !== 100 || ft[1] !== 100) continue;
  /* Plating guessed from a folder name is not plating: a tile may only claim a
     side faces space when the hull curve is drawn on it. */
  if (tile.source === "folder") continue;
  const src = join(tiles, `${path.slice(0, -4)}.webp`);
  if (!existsSync(src)) continue;
  const id = name(path);
  cpSync(src, join(out, "t", `${id}.webp`));
  bytes += readFileSync(src).length;
  index.push({ id, roles: tile.roles ?? [], label: tile.label ?? "", set: tile.set ?? "" });
}

writeFileSync(
  join(out, "deck.json"),
  `${JSON.stringify(
    {
      note: "Generated by tools/deck/bake.mjs. Do not edit.",
      pxPerFoot: 4,
      deckFeet: 100,
      bleedFeet: 10,
      tiles: index.sort((a, b) => (a.id < b.id ? -1 : 1)),
    },
    null,
    1,
  )}\n`,
);

const licence = join(tiles, "LICENCE.md");
if (existsSync(licence)) cpSync(licence, join(out, "LICENCE.md"));

console.log(`${String(index.length)} tiles, ${(bytes / 1e6).toFixed(1)} MB → public/deck/`);
