#!/usr/bin/env python3
"""
Bake a downscaled tile set the game can ship.

The map generator can place any tile the taxonomy classified, so a build that
generates ships cannot get away with copying the handful one deck happens to
use. The whole classified set at source resolution is far too large to ship —
but it does not need to be: the tiles are drawn under the hex lattice, blurred
and held at low opacity, where a fraction of the detail survives anyway.

This writes a separate, downscaled *version* of the artwork. It is a derivative
work, so it carries its own notice: see the README.md and LICENCE.md written
alongside it.

**Four pixels to the foot is not an arbitrary default.** Map generation
rasterises a hull at exactly that, so at 4 px/ft the tiles go down one for one
with no resampling, and the rooms that come out match the source artwork
exactly. Measured on one ship: 4 px/ft finds the same 26 compartments and the
same 44,810 sq ft of floor as the full-resolution art, while 3 px/ft finds 33
and 2 px/ft finds 53 — thin walls go sub-pixel, smear, and cut rooms in half.
It is resolution that does this, not compression: lossless at 2 px/ft is no
better than quality 70.

    python3 scripts/bake_tile_atlas.py            # default 3 px per foot
    python3 scripts/bake_tile_atlas.py --px-per-foot 2 --quality 70
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    sys.exit("Pillow is required: pip install pillow")

SOURCE_PX_PER_FOOT = 12

README = """# Downscaled geomorph tiles

**This is not the original artwork.** It is a reduced-resolution derivative,
generated by `scripts/bake_tile_atlas.py`, and it exists only so a built game
can draw a ship's deck plan without shipping the full library.

- **Original:** Starship Geomorphs / RPG Mobius Geomorphs, by Robert Pearce,
  screen colouring by Eric B. Smith — <https://rpgmobius.com/geomorphs>
- **Licence:** Creative Commons Attribution-NonCommercial 4.0 International
  (CC BY-NC 4.0). See [LICENCE.md](LICENCE.md).
- **Changes made:** downscaled from {source} px per foot to {target} px per
  foot and re-encoded as WebP with an alpha channel. Nothing else — no
  recolouring, no cropping, no rearrangement.

The full-resolution library is **not** committed anywhere in this repository.
Fetch it yourself with `vuvko_works/fetch_geomorphs.py`, then run the bake
script to regenerate this folder.

Anything built with these tiles has to stay **non-commercial**.

{count} tiles, {size}. Regenerate with:

```
python3 scripts/bake_tile_atlas.py
```
"""

LICENCE = """# Licence for the tiles in this folder

These files are a downscaled derivative of the **Starship Geomorphs** artwork
by **Robert Pearce**, in the screen colouring prepared by **Eric B. Smith**,
distributed as *RPG Mobius Geomorphs* at <https://rpgmobius.com/geomorphs>.

They are used here under

> **Creative Commons Attribution-NonCommercial 4.0 International
> (CC BY-NC 4.0)**

- Deed (human-readable summary): <https://creativecommons.org/licenses/by-nc/4.0/>
- Legal code (the licence itself): <https://creativecommons.org/licenses/by-nc/4.0/legalcode>

## What the licence requires of anything built on these files

**Attribution.** Credit Robert Pearce and Eric B. Smith, link to the licence,
and say that changes were made. This project does so on its credits screen and
in `vuvko_works/ATTRIBUTION.md`.

**NonCommercial.** You may not use this material, or anything derived from it,
for commercial purposes. This game is and must remain non-commercial.

**Indicating changes.** The files here are modified: they have been downscaled
from the source resolution and re-encoded as WebP. No other change was made.

**No additional restrictions.** Nothing here adds terms beyond the licence.

## Note

This file records the licence the material arrives under; it is not itself the
licence text. The authoritative legal code lives at the URL above. If you are
redistributing this folder, take the legal code with it.
"""


def load_wanted(index: Path, taxonomy: Path) -> list[str]:
    """Every tile the game can actually put on a deck.

    Read the built index rather than the taxonomy. The taxonomy is every tile
    that was *classified*, which is neither what ships nor what can be placed:
    it still contains the fuel intakes the generator is told to avoid, and it
    contains no overlays at all, because an overlay has no geometry to classify
    and is only ever drawn over a base. Baking the taxonomy therefore shipped
    195 tiles nothing would ever ask for and left out the 453 that hold the
    furniture.
    """
    if index.exists():
        doc = json.loads(index.read_text())
        return sorted(tile["path"] for tile in doc["tiles"])

    doc = json.loads(taxonomy.read_text())
    tiles = doc["tiles"] if isinstance(doc, dict) and "tiles" in doc else doc
    return sorted(tiles)


def human(size: int) -> str:
    if size > 1_000_000:
        return f"{size / 1_000_000:.1f} MB"
    return f"{size / 1000:.0f} KB"


def main() -> None:
    here = Path(__file__).resolve().parent
    root = here.parent
    shared = root.parent

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tiles", type=Path, default=shared / "geomorphs")
    parser.add_argument("--taxonomy", type=Path, default=shared / "tiles.taxonomy.json")
    parser.add_argument(
        "--index", type=Path, default=root / "src" / "assets" / "tiles" / "manifest.json"
    )
    parser.add_argument("--out", type=Path, default=root / "public" / "geomorphs")
    parser.add_argument("--px-per-foot", type=float, default=4.0)
    parser.add_argument("--quality", type=int, default=60)
    parser.add_argument("--limit", type=int, default=0, help="stop after N tiles, for a quick look")
    args = parser.parse_args()

    if not args.tiles.exists():
        sys.exit(
            f"No tile library at {args.tiles}.\n"
            "It is fetched, not committed: cd .. && python3 fetch_geomorphs.py"
        )

    wanted = load_wanted(args.index, args.taxonomy)
    if args.limit:
        wanted = wanted[: args.limit]

    if args.out.exists():
        shutil.rmtree(args.out)
    args.out.mkdir(parents=True)

    scale = args.px_per_foot / SOURCE_PX_PER_FOOT
    written = 0
    missing = 0
    total = 0

    for relative in wanted:
        source = args.tiles / relative
        if not source.exists():
            missing += 1
            continue
        image = Image.open(source).convert("RGBA")
        size = (max(1, round(image.width * scale)), max(1, round(image.height * scale)))
        image = image.resize(size, Image.LANCZOS)

        target = (args.out / relative).with_suffix(".webp")
        target.parent.mkdir(parents=True, exist_ok=True)
        image.save(target, "WEBP", quality=args.quality, method=5)
        total += target.stat().st_size
        written += 1
        if written % 200 == 0:
            print(f"  {written}/{len(wanted)}  {human(total)}", flush=True)

    # What the renderer needs to know about this bake. Assuming the source
    # resolution is exactly the bug this file exists to prevent: a downscaled
    # tile read as full resolution draws at a fraction of its size.
    (args.out / "atlas.json").write_text(
        json.dumps(
            {
                "pxPerFoot": args.px_per_foot,
                "sourcePxPerFoot": SOURCE_PX_PER_FOOT,
                "bleedFeet": 10,
                "tiles": written,
                "format": "webp",
            },
            indent=2,
        )
        + "\n"
    )

    (args.out / "README.md").write_text(
        README.format(
            source=SOURCE_PX_PER_FOOT,
            target=args.px_per_foot,
            count=written,
            size=human(total),
        )
    )
    (args.out / "LICENCE.md").write_text(LICENCE)

    print(f"{written} tiles -> {args.out}  ({human(total)})")
    if missing:
        print(f"{missing} classified tiles were not on disk")


if __name__ == "__main__":
    main()
